id = "codebook"
name = "Codebook Spell Checker"
version = "0.2.7"
description = "ðŸ“’ A fast, code aware spell checker."
authors = ["Bo"]
license = "MIT"
schema_version = 1
repository = "https://github.com/blopker/codebook"

[language_servers.codebook]
name = "codebook"
languages = [
    "C",
    "C++",
    "CSS",
    "CSharp",
    "Elixir",
    "Erlang",
    "Go",
    "HTML",
    "Haskell",
    "Java",
    "JavaScript React",
    "JavaScript",
    "LaTeX",
    "Lua",
    "Markdown",
    "Odin",
    "PHP",
    "Plain Text",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "Shell Script",
    "Swift",
    "TOML",
    "TSX",
    "TypeScript React",
    "TypeScript",
    "Typst",
    "Zig"
]
